name: Test

on: [push, pull_request]

jobs:

  build:
  # We want to run on external PRs, but not on our own internal PRs as they'll be run
  # by the push to the branch. Without this if check, checks are duplicated since
  # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install pytest coverage

      - name: Test for files
        run: |
          test -d ./lessons/best-practices
          test -f ./lessons/best-practices/examples.py
          test -f ./lessons/best-practices/test_examples.py

      - name: Run pytest and coverage
        run: coverage run -m pytest

      - name: Show coverage report
        run: coverage report
